name = "nodehub-modern"
compatibility_date = "2026-02-27"
pages_build_output_dir = "dist"

[vars]
# ADMIN_KEY = "replace-me"

# [[kv_namespaces]]
# binding = "NODEHUB_KV"
# id = "<prod-kv-id>"
# preview_id = "<preview-kv-id>"